# Enable Apply Cilium Config Job
applyConfigToExistingPods:
  enabled: true

# Hubble Ingress
hubble:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt

    
